name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku login
      - name: Add Heroku remote to git repo
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku git:remote -a paved-road
      - name: Set git username and email
        run: |
          git config user.name $(git log -1 --format='%aN')                                                                                           ─╯
          git config user.email $(git log -1 --format='%aE')
          git config -l
      - name: Push to Heroku repository
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: git push heroku main
